apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dlgarcia-integrate
namePrefix: dlgarcia-

resources:
- ../../baseline

patches:
- path: pod-deploy.yaml
- path: svc-deploy.yaml
